/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReadingService } from "../reading.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReadingCreateInput } from "./ReadingCreateInput";
import { Reading } from "./Reading";
import { ReadingFindManyArgs } from "./ReadingFindManyArgs";
import { ReadingWhereUniqueInput } from "./ReadingWhereUniqueInput";
import { ReadingUpdateInput } from "./ReadingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReadingControllerBase {
  constructor(
    protected readonly service: ReadingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Reading })
  @nestAccessControl.UseRoles({
    resource: "Reading",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReading(
    @common.Body() data: ReadingCreateInput
  ): Promise<Reading> {
    return await this.service.createReading({
      data: {
        ...data,

        esgMetric: data.esgMetric
          ? {
              connect: data.esgMetric,
            }
          : undefined,

        ioTDevice: data.ioTDevice
          ? {
              connect: data.ioTDevice,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        esgMetric: {
          select: {
            id: true,
          },
        },

        id: true,

        ioTDevice: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Reading] })
  @ApiNestedQuery(ReadingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Reading",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async readings(@common.Req() request: Request): Promise<Reading[]> {
    const args = plainToClass(ReadingFindManyArgs, request.query);
    return this.service.readings({
      ...args,
      select: {
        createdAt: true,

        esgMetric: {
          select: {
            id: true,
          },
        },

        id: true,

        ioTDevice: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Reading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reading",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reading(
    @common.Param() params: ReadingWhereUniqueInput
  ): Promise<Reading | null> {
    const result = await this.service.reading({
      where: params,
      select: {
        createdAt: true,

        esgMetric: {
          select: {
            id: true,
          },
        },

        id: true,

        ioTDevice: {
          select: {
            id: true,
          },
        },

        timestamp: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Reading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reading",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReading(
    @common.Param() params: ReadingWhereUniqueInput,
    @common.Body() data: ReadingUpdateInput
  ): Promise<Reading | null> {
    try {
      return await this.service.updateReading({
        where: params,
        data: {
          ...data,

          esgMetric: data.esgMetric
            ? {
                connect: data.esgMetric,
              }
            : undefined,

          ioTDevice: data.ioTDevice
            ? {
                connect: data.ioTDevice,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          esgMetric: {
            select: {
              id: true,
            },
          },

          id: true,

          ioTDevice: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Reading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Reading",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReading(
    @common.Param() params: ReadingWhereUniqueInput
  ): Promise<Reading | null> {
    try {
      return await this.service.deleteReading({
        where: params,
        select: {
          createdAt: true,

          esgMetric: {
            select: {
              id: true,
            },
          },

          id: true,

          ioTDevice: {
            select: {
              id: true,
            },
          },

          timestamp: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
